from django.contrib.gis.db import models


class Establishment(models.Model):
    id = models.IntegerField(primary_key=True)
    premise_name = models.CharField(max_length=255, blank=True)
    county = models.IntegerField()
    state_id = models.BigIntegerField()
    prev_state_id = models.BigIntegerField()
    est_type = models.IntegerField()
    territory = models.IntegerField(null=True)
    premise_address1 = models.CharField(max_length=255, blank=True)
    premise_address2 = models.CharField(max_length=255, blank=True)
    premise_city = models.CharField(max_length=255, blank=True)
    premise_state = models.CharField(max_length=255, blank=True)
    premise_zip = models.CharField(max_length=255, blank=True)
    premise_phone = models.CharField(max_length=255, blank=True)
    emergency_number = models.CharField(max_length=255, blank=True)
    premise_fax = models.CharField(max_length=255, blank=True)
    premise_email = models.CharField(max_length=255, blank=True)
    website = models.CharField(max_length=255, blank=True)
    owner_name = models.CharField(max_length=255, blank=True)
    owner_address1 = models.CharField(max_length=255, blank=True)
    owner_address2 = models.CharField(max_length=255, blank=True)
    owner_city = models.CharField(max_length=255, blank=True)
    owner_state = models.CharField(max_length=255, blank=True)
    owner_zip = models.CharField(max_length=255, blank=True)
    owner_phone = models.CharField(max_length=255, blank=True)
    owner_fax = models.CharField(max_length=255, blank=True)
    owner_email = models.CharField(max_length=255, blank=True)
    mailing_name = models.CharField(max_length=255, blank=True)
    mailing_address1 = models.CharField(max_length=255, blank=True)
    mailing_address2 = models.CharField(max_length=255, blank=True)
    mailing_city = models.CharField(max_length=255, blank=True)
    mailing_state = models.CharField(max_length=255, blank=True)
    mailing_zip = models.CharField(max_length=255, blank=True)
    permit_holder = models.CharField(max_length=255, blank=True)
    manager_name = models.CharField(max_length=255, blank=True)
    manager_phone = models.CharField(max_length=255, blank=True)
    hours_of_operation = models.CharField(max_length=255, blank=True)
    opening_date = models.DateTimeField(null=True)
    closing_date = models.DateTimeField(null=True)
    inactivate_date = models.DateTimeField(null=True)
    reactivate_date = models.DateTimeField(null=True)
    status_change_date = models.DateTimeField(null=True)
    before_after_may93 = models.CharField(max_length=255, blank=True)
    permit_expiration_date = models.DateTimeField(null=True)
    setup_date = models.DateTimeField(null=True)
    update_date = models.DateTimeField(null=True)
    latitude_sum = models.CharField(max_length=255, blank=True)
    longitude_sum = models.CharField(max_length=255, blank=True)
    seats = models.CharField(max_length=255, blank=True)
    comments = models.TextField()
    ehs = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=255, blank=True)
    permit_status = models.CharField(max_length=255, blank=True)
    water = models.CharField(max_length=255, blank=True)
    sewage = models.CharField(max_length=255, blank=True)
    insp_freq = models.CharField(max_length=255, blank=True)
    master_est_number = models.CharField(max_length=255, blank=True)
    federal_id_number = models.CharField(max_length=255, blank=True)
    pay_fee_id = models.CharField(max_length=255, blank=True)
    state_owned_id = models.IntegerField(null=True)
    group_code = models.CharField(max_length=255, blank=True)
    group_code_desc = models.CharField(max_length=255, blank=True)
    owner_type_id = models.IntegerField(null=True)
    renewal_status_id = models.IntegerField(null=True)
    print_permit_id = models.IntegerField(null=True)
    handicap_access_id = models.IntegerField(null=True)
    bond_type_id = models.IntegerField(null=True)
    roster_id = models.CharField(max_length=255, blank=True)
    wic_id = models.IntegerField(null=True)
    food_stamps_id = models.IntegerField(null=True)
    language_id = models.IntegerField(null=True)
    contact_type_id = models.IntegerField(null=True)
    inspection_type_id = models.IntegerField(null=True)
    seasonal_code = models.CharField(max_length=255, blank=True)
    seasonal_desc = models.CharField(max_length=255, blank=True)
    menu_type_id = models.IntegerField(null=True)
    license_type_id = models.IntegerField(null=True)
    certified_manager_id = models.IntegerField(null=True)
    caterer_id = models.IntegerField(null=True)
    drivethru_id = models.IntegerField(null=True)
    licensed_plumber_id = models.IntegerField(null=True)
    owner_phone2 = models.CharField(max_length=255, blank=True)
    fee_amount_sum = models.CharField(max_length=255, blank=True)
    district_id = models.IntegerField(null=True)
    district_name = models.CharField(max_length=255, blank=True)
    home_county_id = models.IntegerField(null=True)
    rpt_area_code = models.CharField(max_length=255, blank=True)
    service_type1_id = models.IntegerField(null=True)
    service_type2_id = models.IntegerField(null=True)
    renewal_sent_date = models.DateTimeField(null=True)
    renewal_received_date = models.DateTimeField(null=True)
    permit_print_date = models.DateTimeField(null=True)
    next_inspection_date = models.DateTimeField(null=True)
    test_expiration_date = models.DateTimeField(null=True)
    last_plan_date = models.DateTimeField(null=True)
    construction_expiration_date = models.DateTimeField(null=True)
    est_quantity1_code = models.CharField(max_length=255, blank=True)
    est_quantity1_desc = models.CharField(max_length=255, blank=True)
    quantity2_units = models.CharField(max_length=255, blank=True)
    est_quantity2_code = models.CharField(max_length=255, blank=True)
    est_quantity2_desc = models.CharField(max_length=255, blank=True)
    census_tract_sum = models.CharField(max_length=255, blank=True)
    delete_mark = models.CharField(max_length=255, blank=True)
    rpt_area_num = models.CharField(max_length=255, blank=True)
    est_type_num = models.CharField(max_length=255, blank=True)
    insp_interval = models.CharField(max_length=255, blank=True)
    permit_condition_id = models.CharField(max_length=255, blank=True)
    permit_conditions = models.TextField()
    owner_website = models.CharField(max_length=255, blank=True)
    cert_fname = models.CharField(max_length=255, blank=True)
    cert_lname = models.CharField(max_length=255, blank=True)
    cert_address1 = models.CharField(max_length=255, blank=True)
    cert_address2 = models.CharField(max_length=255, blank=True)
    cert_city = models.CharField(max_length=255, blank=True)
    cert_state = models.CharField(max_length=255, blank=True)
    cert_zip = models.CharField(max_length=255, blank=True)
    cert_phone1 = models.CharField(max_length=255, blank=True)
    cert_phone2 = models.CharField(max_length=255, blank=True)
    cert_number = models.CharField(max_length=255, blank=True)
    cert_trained_by = models.CharField(max_length=255, blank=True)
    disinfectant_id = models.IntegerField(null=True)
    disinfectant_desc = models.CharField(max_length=255, blank=True)
    update_user_id = models.IntegerField(null=True)
    update_user_name = models.CharField(max_length=255, blank=True)
    premise_phone2_ext = models.CharField(max_length=255, blank=True)
    owner_phone2_ext = models.CharField(max_length=255, blank=True)
    cert_phone1_ext = models.CharField(max_length=255, blank=True)
    owner_contact = models.CharField(max_length=255, blank=True)
    cert_email = models.CharField(max_length=255, blank=True)
    pool_filter_type_id = models.IntegerField(null=True)
    pool_filter_type_desc = models.CharField(max_length=255, blank=True)
    dual_main_drains_yn = models.CharField(max_length=255, blank=True)
    local_yn = models.CharField(max_length=255, blank=True)
    property_id = models.IntegerField(null=True)
    permit_ehs_id = models.IntegerField(null=True)
    permit_ehs_num = models.CharField(max_length=255, blank=True)
    number_of_lots_sum = models.CharField(max_length=255, blank=True)
    permit_paid_yn = models.CharField(max_length=255, blank=True)
    tattoo_artists_sum = models.CharField(max_length=255, blank=True)
    corporate_email = models.CharField(max_length=255, blank=True)
    alt_corporate_email = models.CharField(max_length=255, blank=True)
    est_group_id = models.IntegerField(null=True)
    est_group_desc = models.CharField(max_length=255, blank=True)
    noncompliant_cond = models.TextField(blank=True)
    parcel = models.CharField(max_length=255, blank=True)
    smoking_allowed = models.CharField(max_length=255, blank=True)
    risk = models.CharField(max_length=255, blank=True)
    type_description = models.CharField(max_length=255, blank=True)
    rpt_area_desc = models.CharField(max_length=255, blank=True)
    transitional_type_desc = models.CharField(max_length=255, blank=True)
    lat = models.DecimalField(max_digits=17, decimal_places=15, null=True)
    lon = models.DecimalField(max_digits=17, decimal_places=15, null=True)

    location = models.PointField(null=True)
    objects = models.GeoManager()

    def __str__(self):
        return self.premise_name


class Inspection(models.Model):
    id = models.IntegerField(primary_key=True)
    district = models.CharField(max_length=255, blank=True)
    county = models.IntegerField()
    est_id = models.ForeignKey("Establishment", related_name='inspections')
    state_id = models.BigIntegerField()
    request_number = models.CharField(max_length=255, blank=True)
    ehs_id = models.IntegerField(null=True)
    ehs = models.CharField(max_length=255, blank=True)
    territory = models.IntegerField(null=True, blank=True)
    est_type = models.CharField(max_length=255, blank=True)
    insp_type = models.CharField(max_length=255, blank=True)
    insp_date = models.DateTimeField(null=True)
    extra_credit = models.CharField(max_length=255, blank=True)
    grade = models.CharField(max_length=255, blank=True)
    score_sum = models.CharField(max_length=255, blank=True)
    final_score_sum = models.CharField(max_length=255, blank=True)
    seats = models.CharField(max_length=255, blank=True)
    inspection_time_hrs = models.CharField(max_length=255, blank=True)
    inspection_time_min = models.CharField(max_length=255, blank=True)
    sample = models.CharField(max_length=255, blank=True)
    setup_date = models.DateTimeField(null=True)
    update_date = models.DateTimeField(null=True)
    update_user_id = models.IntegerField(null=True, blank=True)
    water = models.CharField(max_length=255, blank=True)
    sewage = models.CharField(max_length=255, blank=True)
    origin = models.CharField(max_length=255, blank=True)
    permit_status_id = models.IntegerField(null=True)
    permit_status = models.CharField(max_length=255, blank=True)
    time_of_inspection_hr = models.CharField(max_length=255, blank=True)
    time_of_inspection_mm = models.CharField(max_length=255, blank=True)
    ampm_of_inspection = models.CharField(max_length=255, blank=True)
    comments = models.TextField(blank=True)
    six_point_demerit = models.CharField(max_length=255, blank=True)
    oss_id = models.IntegerField(null=True)
    rpt_area_code = models.CharField(max_length=255, blank=True)
    rpt_area_desc = models.CharField(max_length=255, blank=True)
    group_code_id = models.IntegerField(null=True, blank=True)
    time_of_inspection = models.CharField(max_length=255, blank=True)
    permit_type_id = models.IntegerField(null=True)
    complaint_section = models.CharField(max_length=255, blank=True)
    epi_type_id = models.IntegerField(null=True, blank=True)
    epi_type_desc = models.CharField(max_length=255, blank=True)
    followup_id = models.CharField(max_length=255, blank=True)
    travel_time_hrs = models.CharField(max_length=255, blank=True)
    travel_time_min = models.CharField(max_length=255, blank=True)
    mileage = models.CharField(max_length=255, blank=True)
    sample_attendance = models.CharField(max_length=255, blank=True)
    void_date = models.DateTimeField(null=True)
    delete_mark = models.CharField(max_length=255, blank=True)
    est_num = models.CharField(max_length=255, blank=True)
    com_num = models.CharField(max_length=255, blank=True)
    oss_num = models.CharField(max_length=255, blank=True)
    ehs_num = models.CharField(max_length=255, blank=True)
    rpt_area_num = models.CharField(max_length=255, blank=True)
    est_type_num = models.CharField(max_length=255, blank=True)
    cdp_est_num = models.CharField(max_length=255, blank=True)
    violations_id = models.IntegerField(null=True)
    permit_status = models.CharField(max_length=255, blank=True)
    comment_sheet_id = models.CharField(max_length=255, blank=True)
    action_code_id = models.IntegerField(null=True)
    action_code_desc = models.CharField(max_length=255, blank=True)
    image_file_path = models.CharField(max_length=255, blank=True)
    image_file_name = models.CharField(max_length=255, blank=True)
    chlorine_sum = models.CharField(max_length=255, blank=True)
    bromine_sum = models.CharField(max_length=255, blank=True)
    biguanide_sum = models.CharField(max_length=255, blank=True)
    water_ph_sum = models.CharField(max_length=255, blank=True)
    water_temp_sum = models.CharField(max_length=255, blank=True)
    smoking_allowed = models.CharField(max_length=255, blank=True)
    classification_id = models.IntegerField(null=True)
    classification_desc = models.CharField(max_length=255, blank=True)
    end_time_of_inspection_hh = models.CharField(max_length=255, blank=True)
    end_time_of_inspection_mm = models.CharField(max_length=255, blank=True)
    end_inspection_ampm = models.CharField(max_length=255, blank=True)
    sent_to_bets_yn = models.CharField(max_length=255, blank=True)
    verification_required_date = models.DateTimeField(null=True)
    inspection_reason_id = models.IntegerField(null=True)
    inspection_reason_desc = models.CharField(max_length=255, blank=True)
    num_rf_inter_viol = models.CharField(max_length=255, blank=True)
    num_repeat_rf_inter_viol = models.CharField(max_length=255, blank=True)
    est_group_id = models.IntegerField(null=True, blank=True)
    est_group_desc = models.CharField(max_length=255, blank=True)
    person_incharge_lname = models.CharField(max_length=255, blank=True)
    person_incharge_fname = models.CharField(max_length=255, blank=True)
    type_description = models.CharField(max_length=255, blank=True)
    code = models.CharField(max_length=255, blank=True)

    objects = models.GeoManager()


class Violation(models.Model):
    id = models.IntegerField(primary_key=True)
    inspection_id = models.ForeignKey("Inspection", related_name='violations')
    item = models.IntegerField()
    weight_sum = models.FloatField()
    critical = models.CharField(max_length=255, blank=True)
    comments = models.TextField(blank=True)
    rpt_area_desc = models.CharField(max_length=255, blank=True)

    objects = models.GeoManager()
