# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Establishment'
        db.create_table('inspections_establishment', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('premise_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('county', self.gf('django.db.models.fields.IntegerField')()),
            ('state_id', self.gf('django.db.models.fields.BigIntegerField')()),
            ('prev_state_id', self.gf('django.db.models.fields.BigIntegerField')()),
            ('est_type', self.gf('django.db.models.fields.IntegerField')()),
            ('territory', self.gf('django.db.models.fields.IntegerField')()),
            ('premise_address1', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_address2', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_city', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_state', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_zip', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_phone', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('emergency_number', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_fax', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_email', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('website', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_address1', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_address2', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_city', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_state', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_zip', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_phone', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_fax', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_email', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mailing_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mailing_address1', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mailing_address2', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mailing_city', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mailing_state', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mailing_zip', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_holder', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('manager_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('manager_phone', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('hours_of_operation', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('opening_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('closing_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('inactivate_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('reactivate_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('status_change_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('before_after_may93', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_expiration_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('setup_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('update_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('latitude_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('longitude_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('seats', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('comments', self.gf('django.db.models.fields.TextField')()),
            ('ehs', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('status', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_status', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('water', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('sewage', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('insp_freq', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('master_est_number', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('federal_id_number', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('pay_fee_id', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('state_owned_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('group_code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('group_code_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('renewal_status_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('print_permit_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('handicap_access_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('bond_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('roster_id', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('wic_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('food_stamps_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('language_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('contact_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('inspection_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('seasonal_code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('seasonal_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('menu_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('license_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('certified_manager_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('caterer_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('drivethru_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('licensed_plumber_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('owner_phone2', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('fee_amount_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('district_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('district_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('home_county_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('rpt_area_code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('service_type1_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('service_type2_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('renewal_sent_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('renewal_received_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('permit_print_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('next_inspection_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('test_expiration_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('last_plan_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('construction_expiration_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('est_quantity1_code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_quantity1_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('quantity2_units', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_quantity2_code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_quantity2_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('census_tract_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('delete_mark', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('rpt_area_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_type_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('insp_interval', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_condition_id', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_conditions', self.gf('django.db.models.fields.TextField')()),
            ('owner_website', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_fname', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_lname', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_address1', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_address2', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_city', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_state', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_zip', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_phone1', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_phone2', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_number', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_trained_by', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('disinfectant_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('disinfectant_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('update_user_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('update_user_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('premise_phone2_ext', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_phone2_ext', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_phone1_ext', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('owner_contact', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cert_email', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('pool_filter_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('pool_filter_type_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('dual_main_drains_yn', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('local_yn', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('property_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('permit_ehs_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('permit_ehs_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('number_of_lots_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_paid_yn', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('tattoo_artists_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('corporate_email', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('alt_corporate_email', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_group_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('est_group_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('noncompliant_cond', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('parcel', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('smoking_allowed', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('risk', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('type_description', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('rpt_area_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('transitional_type_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('lat', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=17, decimal_places=15)),
            ('lon', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=17, decimal_places=15)),
            ('location', self.gf('django.contrib.gis.db.models.fields.PointField')(null=True)),
        ))
        db.send_create_signal('inspections', ['Establishment'])

        # Adding model 'Inspection'
        db.create_table('inspections_inspection', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('district', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('county', self.gf('django.db.models.fields.IntegerField')()),
            ('est_id', self.gf('django.db.models.fields.related.ForeignKey')(related_name='inspections', to=orm['inspections.Establishment'])),
            ('state_id', self.gf('django.db.models.fields.BigIntegerField')()),
            ('request_number', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('ehs_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('ehs', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('territory', self.gf('django.db.models.fields.IntegerField')()),
            ('est_type', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('insp_type', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('insp_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('extra_credit', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('grade', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('score_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('final_score_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('seats', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('inspection_time_hrs', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('inspection_time_min', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('sample', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('setup_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('update_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('update_user_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('water', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('sewage', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('origin', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_status_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('time_of_inspection_hr', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('time_of_inspection_mm', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('ampm_of_inspection', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('comments', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('six_point_demerit', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('oss_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('rpt_area_code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('rpt_area_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('group_code_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('time_of_inspection', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('permit_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('complaint_section', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('epi_type_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('epi_type_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('followup_id', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('travel_time_hrs', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('travel_time_min', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('mileage', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('sample_attendance', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('void_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('delete_mark', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('com_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('oss_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('ehs_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('rpt_area_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_type_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('cdp_est_num', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('violations_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('permit_status', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('comment_sheet_id', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('action_code_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('action_code_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('image_file_path', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('image_file_name', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('chlorine_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('bromine_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('biguanide_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('water_ph_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('water_temp_sum', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('smoking_allowed', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('classification_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('classification_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('end_time_of_inspection_hh', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('end_time_of_inspection_mm', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('end_inspection_ampm', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('sent_to_bets_yn', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('verification_required_date', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('inspection_reason_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('inspection_reason_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('num_rf_inter_viol', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('num_repeat_rf_inter_viol', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('est_group_id', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('est_group_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('person_incharge_lname', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('person_incharge_fname', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('type_description', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('code', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
        ))
        db.send_create_signal('inspections', ['Inspection'])

        # Adding model 'Violation'
        db.create_table('inspections_violation', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('inspection_id', self.gf('django.db.models.fields.related.ForeignKey')(related_name='violations', to=orm['inspections.Inspection'])),
            ('item', self.gf('django.db.models.fields.IntegerField')()),
            ('weight_sum', self.gf('django.db.models.fields.FloatField')()),
            ('critical', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
            ('comments', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('rpt_area_desc', self.gf('django.db.models.fields.CharField')(blank=True, max_length=255)),
        ))
        db.send_create_signal('inspections', ['Violation'])


    def backwards(self, orm):
        # Deleting model 'Establishment'
        db.delete_table('inspections_establishment')

        # Deleting model 'Inspection'
        db.delete_table('inspections_inspection')

        # Deleting model 'Violation'
        db.delete_table('inspections_violation')


    models = {
        'inspections.establishment': {
            'Meta': {'object_name': 'Establishment'},
            'alt_corporate_email': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'before_after_may93': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'bond_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'caterer_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'census_tract_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_address1': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_address2': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_city': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_email': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_fname': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_lname': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_number': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_phone1': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_phone1_ext': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_phone2': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_state': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_trained_by': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cert_zip': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'certified_manager_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'closing_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'comments': ('django.db.models.fields.TextField', [], {}),
            'construction_expiration_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'contact_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'corporate_email': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'county': ('django.db.models.fields.IntegerField', [], {}),
            'delete_mark': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'disinfectant_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'disinfectant_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'district_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'district_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'drivethru_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'dual_main_drains_yn': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'ehs': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'emergency_number': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_group_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_group_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'est_quantity1_code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_quantity1_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_quantity2_code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_quantity2_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_type': ('django.db.models.fields.IntegerField', [], {}),
            'est_type_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'federal_id_number': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'fee_amount_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'food_stamps_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'group_code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'group_code_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'handicap_access_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'home_county_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'hours_of_operation': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'inactivate_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'insp_freq': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'insp_interval': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'inspection_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'language_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'last_plan_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'lat': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '17', 'decimal_places': '15'}),
            'latitude_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'license_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'licensed_plumber_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'local_yn': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'location': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True'}),
            'lon': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '17', 'decimal_places': '15'}),
            'longitude_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mailing_address1': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mailing_address2': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mailing_city': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mailing_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mailing_state': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mailing_zip': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'manager_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'manager_phone': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'master_est_number': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'menu_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'next_inspection_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'noncompliant_cond': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'number_of_lots_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'opening_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'owner_address1': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_address2': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_city': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_contact': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_email': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_fax': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_phone': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_phone2': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_phone2_ext': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_state': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'owner_website': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'owner_zip': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'parcel': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'pay_fee_id': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_condition_id': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_conditions': ('django.db.models.fields.TextField', [], {}),
            'permit_ehs_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'permit_ehs_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_expiration_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'permit_holder': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_paid_yn': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_print_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'permit_status': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'pool_filter_type_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'pool_filter_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'premise_address1': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_address2': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_city': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_email': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_fax': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_phone': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_phone2_ext': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_state': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'premise_zip': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'prev_state_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'print_permit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'property_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'quantity2_units': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'reactivate_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'renewal_received_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'renewal_sent_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'renewal_status_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'risk': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'roster_id': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'rpt_area_code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'rpt_area_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'rpt_area_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'seasonal_code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'seasonal_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'seats': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'service_type1_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'service_type2_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'setup_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'sewage': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'smoking_allowed': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'state_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'state_owned_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'status_change_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'tattoo_artists_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'territory': ('django.db.models.fields.IntegerField', [], {}),
            'test_expiration_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'transitional_type_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'type_description': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'update_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'update_user_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'update_user_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'water': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'website': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'wic_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        'inspections.inspection': {
            'Meta': {'object_name': 'Inspection'},
            'action_code_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'action_code_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'ampm_of_inspection': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'biguanide_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'bromine_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'cdp_est_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'chlorine_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'classification_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'classification_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'com_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'comment_sheet_id': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'comments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'complaint_section': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'county': ('django.db.models.fields.IntegerField', [], {}),
            'delete_mark': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'district': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'ehs': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'ehs_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'ehs_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'end_inspection_ampm': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'end_time_of_inspection_hh': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'end_time_of_inspection_mm': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'epi_type_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'epi_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'est_group_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_group_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'est_id': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'inspections'", 'to': "orm['inspections.Establishment']"}),
            'est_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_type': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'est_type_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'extra_credit': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'final_score_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'followup_id': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'grade': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'group_code_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'image_file_name': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'image_file_path': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'insp_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'insp_type': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'inspection_reason_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'inspection_reason_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'inspection_time_hrs': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'inspection_time_min': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'mileage': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'num_repeat_rf_inter_viol': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'num_rf_inter_viol': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'origin': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'oss_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'oss_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_status': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'permit_status_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'permit_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'person_incharge_fname': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'person_incharge_lname': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'request_number': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'rpt_area_code': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'rpt_area_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'rpt_area_num': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'sample': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'sample_attendance': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'score_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'seats': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'sent_to_bets_yn': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'setup_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'sewage': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'six_point_demerit': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'smoking_allowed': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'state_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'territory': ('django.db.models.fields.IntegerField', [], {}),
            'time_of_inspection': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'time_of_inspection_hr': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'time_of_inspection_mm': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'travel_time_hrs': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'travel_time_min': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'type_description': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'update_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'update_user_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'verification_required_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'violations_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'void_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'water': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'water_ph_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'water_temp_sum': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'})
        },
        'inspections.violation': {
            'Meta': {'object_name': 'Violation'},
            'comments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'critical': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'inspection_id': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'violations'", 'to': "orm['inspections.Inspection']"}),
            'item': ('django.db.models.fields.IntegerField', [], {}),
            'rpt_area_desc': ('django.db.models.fields.CharField', [], {'blank': 'True', 'max_length': '255'}),
            'weight_sum': ('django.db.models.fields.FloatField', [], {})
        }
    }

    complete_apps = ['inspections']