# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):

        # Changing field 'Establishment.territory'
        db.alter_column('inspections_establishment', 'territory', self.gf('django.db.models.fields.IntegerField')(null=True))

    def backwards(self, orm):

        # User chose to not deal with backwards NULL issues for 'Establishment.territory'
        raise RuntimeError("Cannot reverse this migration. 'Establishment.territory' and its values cannot be restored.")
        
        # The following code is provided here to aid in writing a correct migration
        # Changing field 'Establishment.territory'
        db.alter_column('inspections_establishment', 'territory', self.gf('django.db.models.fields.IntegerField')())

    models = {
        'inspections.establishment': {
            'Meta': {'object_name': 'Establishment'},
            'alt_corporate_email': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'before_after_may93': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'bond_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'caterer_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'census_tract_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_address2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_city': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_email': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_fname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_lname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_number': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_phone1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_phone1_ext': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_phone2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_state': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_trained_by': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cert_zip': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'certified_manager_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'closing_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'comments': ('django.db.models.fields.TextField', [], {}),
            'construction_expiration_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'contact_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'corporate_email': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'county': ('django.db.models.fields.IntegerField', [], {}),
            'delete_mark': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'disinfectant_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'disinfectant_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'district_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'district_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'drivethru_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'dual_main_drains_yn': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'ehs': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'emergency_number': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_group_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_group_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'est_quantity1_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_quantity1_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_quantity2_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_quantity2_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_type': ('django.db.models.fields.IntegerField', [], {}),
            'est_type_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'federal_id_number': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'fee_amount_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'food_stamps_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'group_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'group_code_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'handicap_access_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'home_county_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'hours_of_operation': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'inactivate_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'insp_freq': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'insp_interval': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'inspection_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'language_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'last_plan_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'lat': ('django.db.models.fields.DecimalField', [], {'decimal_places': '15', 'max_digits': '17', 'null': 'True'}),
            'latitude_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'license_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'licensed_plumber_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'local_yn': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'location': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True'}),
            'lon': ('django.db.models.fields.DecimalField', [], {'decimal_places': '15', 'max_digits': '17', 'null': 'True'}),
            'longitude_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mailing_address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mailing_address2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mailing_city': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mailing_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mailing_state': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mailing_zip': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'manager_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'manager_phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'master_est_number': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'menu_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'next_inspection_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'noncompliant_cond': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'number_of_lots_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'opening_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'owner_address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_address2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_city': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_contact': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_email': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_fax': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_phone2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_phone2_ext': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_state': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'owner_website': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'owner_zip': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'parcel': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'pay_fee_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_condition_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_conditions': ('django.db.models.fields.TextField', [], {}),
            'permit_ehs_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'permit_ehs_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_expiration_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'permit_holder': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_paid_yn': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_print_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'permit_status': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'pool_filter_type_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'pool_filter_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'premise_address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_address2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_city': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_email': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_fax': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_phone2_ext': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_state': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'premise_zip': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'prev_state_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'print_permit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'property_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'quantity2_units': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'reactivate_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'renewal_received_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'renewal_sent_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'renewal_status_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'risk': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'roster_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'rpt_area_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'rpt_area_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'rpt_area_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'seasonal_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'seasonal_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'seats': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'service_type1_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'service_type2_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'setup_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'sewage': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'smoking_allowed': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'state_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'state_owned_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'status_change_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'tattoo_artists_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'territory': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'test_expiration_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'transitional_type_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'type_description': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'update_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'update_user_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'update_user_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'water': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'website': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'wic_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        'inspections.inspection': {
            'Meta': {'object_name': 'Inspection'},
            'action_code_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'action_code_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'ampm_of_inspection': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'biguanide_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'bromine_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'cdp_est_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'chlorine_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'classification_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'classification_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'com_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'comment_sheet_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'comments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'complaint_section': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'county': ('django.db.models.fields.IntegerField', [], {}),
            'delete_mark': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'district': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'ehs': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'ehs_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'ehs_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'end_inspection_ampm': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'end_time_of_inspection_hh': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'end_time_of_inspection_mm': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'epi_type_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'epi_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'est_group_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_group_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'est_id': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'inspections'", 'to': "orm['inspections.Establishment']"}),
            'est_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'est_type_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'extra_credit': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'final_score_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'followup_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'grade': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'group_code_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'image_file_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'image_file_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'insp_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'insp_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'inspection_reason_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'inspection_reason_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'inspection_time_hrs': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'inspection_time_min': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'mileage': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'num_repeat_rf_inter_viol': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'num_rf_inter_viol': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'origin': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'oss_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'oss_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_status': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'permit_status_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'permit_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'person_incharge_fname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'person_incharge_lname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'request_number': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'rpt_area_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'rpt_area_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'rpt_area_num': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'sample': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'sample_attendance': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'score_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'seats': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'sent_to_bets_yn': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'setup_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'sewage': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'six_point_demerit': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'smoking_allowed': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'state_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'territory': ('django.db.models.fields.IntegerField', [], {}),
            'time_of_inspection': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'time_of_inspection_hr': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'time_of_inspection_mm': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'travel_time_hrs': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'travel_time_min': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'type_description': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'update_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'update_user_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'verification_required_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'violations_id': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'void_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'water': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'water_ph_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'water_temp_sum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'})
        },
        'inspections.violation': {
            'Meta': {'object_name': 'Violation'},
            'comments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'critical': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'inspection_id': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'violations'", 'to': "orm['inspections.Inspection']"}),
            'item': ('django.db.models.fields.IntegerField', [], {}),
            'rpt_area_desc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'weight_sum': ('django.db.models.fields.FloatField', [], {})
        }
    }

    complete_apps = ['inspections']